global_costmap:
  global_frame: /map
  update_frequency: 1.5
  publish_frequency: 1.5
  static_map: true
  rolling_window: false
  unknown_cost_value: 0
  publish_voxel_map: false
  lethal_cost_threshold: 100
  map_topic: /map
  map_type: costmap
  
  track_unknow_space: false
  
